services:
  db:
    restart: unless-stopped

  api:
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  agent:
    restart: unless-stopped

  client:
    restart: unless-stopped
