services:
  db:
    ports:
      - "5432:5432"

  api:
    ports:
      - "5100:5100"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  agent:
    ports:
      - "8000:8000"

  chat-db:
    ports:
      - "5433:5432"
