import type { FC, PropsWithChildren } from "react";
import { useMemo } from "react";
import {
    RuntimeAdapterProvider,
    useAui,
    type RemoteThreadListAdapter,
    type ThreadHistoryAdapter,
    type ThreadMessage,
    SimpleImageAttachmentAdapter,
    SimpleTextAttachmentAdapter,
    CompositeAttachmentAdapter,
} from "@assistant-ui/react";
import { createAssistantStream } from "assistant-stream";
import MarkdownAttachmentAdapter from "@/adapters/MarkdownAttachmentAdapter";
import {
    listChats,
    createChat,
    getChat,
    patchChat,
    deleteChat,
    getMessages,
    appendMessage,
    generateTitle,
    fallbackTitle,
} from "@/api/store";

/**
 * Chat persistence wiring for assistant-ui: how attachments are decoded, how a
 * thread's message history is loaded/saved, and how the thread list maps to the
 * agent's `/agent/store` routes.
 */

export const attachmentAdapter = new CompositeAttachmentAdapter([
    new SimpleImageAttachmentAdapter(),
    new MarkdownAttachmentAdapter(),
    new SimpleTextAttachmentAdapter(),
]);

/**
 * A File can't survive JSON persistence as it round-trips into a `{}` that crashes
 * `URL.createObjectURL`. Drop it so a restored image attachment renders from its
 * data-URL content instead.
 */
export function stripAttachmentFiles(message: ThreadMessage): ThreadMessage {
    if (!("attachments" in message) || !message.attachments?.length) return message;
    return {
        ...message,
        attachments: message.attachments.map((a) => {
            const copy = { ...a };
            delete (copy as { file?: unknown }).file;
            return copy;
        }),
    } as ThreadMessage;
}

/**
 * Per-thread history adapter, injected into each thread's runtime via context.
 * Mirrors assistant-ui's cloud adapter: the remoteId is read from the active thread
 * list item, and `initialize()` is awaited before the first write so a brand-new
 * thread is created server-side exactly once.
 */
const HistoryProvider: FC<PropsWithChildren> = ({ children }) => {
    const aui = useAui();
    const history = useMemo<ThreadHistoryAdapter>(
        () => ({
            async load() {
                const remoteId = aui.threadListItem().getState().remoteId;
                if (!remoteId) return { messages: [] };
                return getMessages(remoteId);
            },
            async append(item) {
                const { remoteId } = await aui.threadListItem().initialize();
                await appendMessage(remoteId, { ...item, message: stripAttachmentFiles(item.message) });
            },
        }),
        [aui],
    );
    return (
        <RuntimeAdapterProvider adapters={{ history }}>
            {children}
        </RuntimeAdapterProvider>
    );
};

/**
 * Thread-list persistence backed by the agent's /agent/store endpoints.
 * Each method maps 1:1 to a backend route.
 * Titles are generated by the LLM on first turn (falling back to a truncated message) and persisted via `rename`.
 */
export const remoteThreadListAdapter: RemoteThreadListAdapter = {
    async list() {
        const { threads } = await listChats();
        return {
            // status is always "regular" (the backend has no archive concept)
            threads: threads.map((t) => ({
                status: "regular",
                remoteId: t.remoteId,
                title: t.title ?? undefined,
            })),
        };
    },
    async initialize() {
        const { remoteId, externalId } = await createChat();
        return { remoteId, externalId: externalId ?? undefined };
    },
    async rename(remoteId, newTitle) {
        await patchChat(remoteId, newTitle);
    },
    // archive isn't surfaced in the UI; satisfy the interface as no-ops.
    async archive() {},
    async unarchive() {},
    async delete(remoteId) {
        await deleteChat(remoteId);
    },
    async fetch(threadId) {
        const t = await getChat(threadId);
        return { status: "regular", remoteId: t.remoteId, title: t.title ?? undefined };
    },
    async generateTitle(remoteId, messages) {
        let title: string;
        try {
            title = (await generateTitle(messages));
        } catch {
            // llm title not available for whatever reason
            title = fallbackTitle(messages);
        }
        await patchChat(remoteId, title);
        return createAssistantStream((controller) => {
            controller.appendText(title);
        });
    },
    unstable_Provider: HistoryProvider,
};
